### ISSUE TITLE
Missing Dependencies

### ISSUE THREAD

**Issue by LeWaldm** [ritvikgupta199/DASHA#1]
Thank you for publishing your code.

To successfully run `/src/main_dasha.py` I needed to install the following dependencies in addition to the ones specified in `requirements.txt`:

scikit-learn
ray[tune]
datasets
rasterio
pytorch-lightning
matplotlib

If you are interested in any more information, please let me know.

**Comment by ritvikgupta199** [comment]
Thank you for pointing this out! We've updated the `requirements.txt` file to include these dependencies. Let us know if you face any other issues!
